stages:
  - prepare
  - build
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  PILOT_USERNAME: "apple.railwaymen.ci@gmail.com"
  SIGH_USERNAME: "apple.railwaymen.ci@gmail.com"

cache:
  key: "bundle_dependencies"
  paths:
  - vendor

.setup: &setup
  - export
  - cd Example
  - rvm use --create 2.6.0@${CI_PROJECT_NAME}
  - gem install bundler:2.1.1
  - bundle install --path=/Users/xcodeserver/gitlab-runner/builds/shared/${CI_PROJECT_NAME}/gems
  - bundle exec pod install || bundle exec pod install --repo-update

prepare_proj:
  stage: prepare
  script:
    *setup
  artifacts:
    name: "Bundle_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 day
    paths:
      - Example/Pods/*
      - Example/JSONFactorable.xcworkspace
  when: on_success
  tags:
    - ios

test_project:
  stage: build
  before_script:
    *setup
  script:
    - bundle exec fastlane test
  after_script:
    - killall "Simulator" || true
  artifacts:
    name: "Tests_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 week
  when: on_success
  dependencies:
    - prepare_proj
  tags:
    - ios_simulator
  coverage: '/JSONFactorable\.framework\D*\|\D*([\d\.]*)\%/'

deploy_pod:
  stage: deploy
  before_script:
    *setup
  script:
    - bundle exec fastlane deploy
  artifacts:
    name: "Deploy_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 week
  when: manual
  dependencies:
    - test_project
  only:
    - /[\d\.]*/
  except:
    - branches
  tags:
    - ios
