default_platform(:ios)

podspec_path = "../JSONFactorable.podspec"
project = "JSONFactorable.xcodeproj"
workspace = "JSONFactorable.xcworkspace"
scheme = "JSONFactorable-Example"
podfile_path = "Podfile.lock"

platform :ios do

  before_all do
    xcversion(version: "11.3")
    if ENV['CI_PIPELINE_ID']
      increment_build_number(build_number: "#{ENV['CI_PIPELINE_ID']}")
    end
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end

  #PUBLIC LANES
  desc "Run unit tests"
  lane :test do
    check_style
    scan
    xcov(
      scheme: scheme,
      workspace: workspace,
      json_report: true,
      markdown_report: true,
      output_directory: "output/tests/coverage/xcov",
      skip_slack: true
    )
    slather(
      scheme: scheme,
      workspace: workspace,
      proj: project,
      html: true,
      output_directory: "output/tests/coverage/slather",
      binary_basename: "JSONFactorable"
    )
  end

  desc "Deploy podspec"
  lane :deploy do
    pod_lib_lint(
      private: true,
      podspec: podspec_path
    )
    pod_push(path: podspec_path, repo: "railwaymen-open-rwm_podspec")
  end

  #PRIVATE LANES
  private_lane :check_style do
    output_path="output/lint"
    output_file="#{output_path}/swiftlint.txt"

    sh("cd .. && mkdir -p #{output_path}")
    ENV["PATH"] = ["Pods/SwiftLint", ENV["PATH"]].join(":")
    swiftlint(output_file: output_file, reporter: "emoji")
  end
end
